<<<<<<< HEAD
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

=======
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

>>>>>>> HR
